// <auto-generated />
using System;
using DesliderClaude.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesliderClaude.Data.Migrations
{
    [DbContext(typeof(DesliderClaudeDbContext))]
    [Migration("20260420151633_AddBggImports")]
    partial class AddBggImports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("DesliderClaude.Core.Models.BggGame", b =>
                {
                    b.Property<int>("BggGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxPlayTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinPlayTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedPlayerCountsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("BggGameId");

                    b.ToTable("BggGames");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.BggImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SourceType", "SourceRef")
                        .IsUnique();

                    b.ToTable("BggImports");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.BggImportItem", b =>
                {
                    b.Property<Guid>("BggImportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BggGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BggImportId", "BggGameId");

                    b.HasIndex("BggGameId");

                    b.ToTable("BggImportItems");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameNightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameNightId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.GameNight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.ToTable("GameNights");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Swipe", b =>
                {
                    b.Property<Guid>("VoterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SwipedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Yes")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoterId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Swipes");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameNightId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoterToken")
                        .IsUnique();

                    b.HasIndex("GameNightId", "UserId");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.BggImport", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.BggImportItem", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.BggGame", "Game")
                        .WithMany("ImportItems")
                        .HasForeignKey("BggGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesliderClaude.Core.Models.BggImport", "Import")
                        .WithMany("Items")
                        .HasForeignKey("BggImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Import");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.ExternalLogin", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Game", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.GameNight", "GameNight")
                        .WithMany("Games")
                        .HasForeignKey("GameNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNight");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.GameNight", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Swipe", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.Game", "Game")
                        .WithMany("Swipes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesliderClaude.Core.Models.Voter", "Voter")
                        .WithMany("Swipes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Voter", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.GameNight", "GameNight")
                        .WithMany("Voters")
                        .HasForeignKey("GameNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesliderClaude.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameNight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.BggGame", b =>
                {
                    b.Navigation("ImportItems");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.BggImport", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Game", b =>
                {
                    b.Navigation("Swipes");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.GameNight", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Voters");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.User", b =>
                {
                    b.Navigation("ExternalLogins");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Voter", b =>
                {
                    b.Navigation("Swipes");
                });
#pragma warning restore 612, 618
        }
    }
}
