// <auto-generated />
using System;
using DesliderClaude.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesliderClaude.Data.Migrations
{
    [DbContext(typeof(DesliderClaudeDbContext))]
    [Migration("20260417235246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("DesliderClaude.Core.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameNightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameNightId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.GameNight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.ToTable("GameNights");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Swipe", b =>
                {
                    b.Property<Guid>("VoterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SwipedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Yes")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoterId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Swipes");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameNightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameNightId");

                    b.HasIndex("VoterToken")
                        .IsUnique();

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Game", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.GameNight", "GameNight")
                        .WithMany("Games")
                        .HasForeignKey("GameNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNight");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Swipe", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.Game", "Game")
                        .WithMany("Swipes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesliderClaude.Core.Models.Voter", "Voter")
                        .WithMany("Swipes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Voter", b =>
                {
                    b.HasOne("DesliderClaude.Core.Models.GameNight", "GameNight")
                        .WithMany("Voters")
                        .HasForeignKey("GameNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNight");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Game", b =>
                {
                    b.Navigation("Swipes");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.GameNight", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Voters");
                });

            modelBuilder.Entity("DesliderClaude.Core.Models.Voter", b =>
                {
                    b.Navigation("Swipes");
                });
#pragma warning restore 612, 618
        }
    }
}
